apiVersion: cis.f5.com/v1
kind: F5BigIpCtlr
metadata:
  name: f5-server
  namespace: default
spec:
  args:
    log_as3_response: true
    manage_routes: true
    agent: as3
    log_level: DEBUG
    route_vserver_addr: 172.16.1.4
    bigip_partition: ocp
    openshift_sdn_name: /Common/openshift_vxlan
    bigip_url: 10.145.64.213
    insecure: true
    pool-member-type: cluster
  bigip_login_secret: f5-bigip-ctlr-login
  image:
    pullPolicy: Always
    repo: k8s-bigip-ctlr
    tag: latest
    user: f5networks
  namespace: kube-system
  rbac:
    create: true
  resources: {}
  serviceAccount:
    create: true
    name: null
