apiVersion: cis.f5.com/v1
kind: F5BigIpCtlr
metadata:
  name: f5-server
spec:
  # Default values copied from <project_dir>/helm-charts/f5-bigip-ctlr/values.yaml
  
  args:
    bigip_partition: f5-bigip-ctlr
    bigip_url: null
  bigip_login_secret: f5-bigip-ctlr-login
  image:
    pullPolicy: Always
    repo: k8s-bigip-ctlr
    tag: latest
    user: f5networks
  namespace: kube-system
  rbac:
    create: true
  resources: {}
  serviceAccount:
    create: true
    name: null
  
