apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5-bigip-ctlr-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: f5-bigip-ctlr-operator
  template:
    metadata:
      labels:
        name: f5-bigip-ctlr-operator
    spec:
      serviceAccountName: f5-bigip-ctlr-operator
      containers:
        - name: f5-bigip-ctlr-operator
          # Replace this with the built image name
          image: f5-cis-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "f5-bigip-ctlr-operator"
